fixtures:
  repositories:
    'concat':
      'repo': 'git://github.com/puppetlabs/puppetlabs-concat.git'
      'ref': '1.2.1'
    'inifile':  'git://github.com/puppetlabs/puppetlabs-inifile.git'
    'keystone': 'git://github.com/stackforge/puppet-keystone.git'
    'mysql':
      repo: 'git://github.com/puppetlabs/puppetlabs-mysql.git'
      ref: 'origin/2.2.x'
    'openstacklib': 'git://github.com/stackforge/puppet-openstacklib.git'
    'postgresql':
      repo: 'git://github.com/puppetlabs/puppet-postgresql.git'
      ref: '2.5.0'
    'stdlib': 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
  symlinks:
    'tuskar': "#{source_dir}"
